version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "Build phase completed"

artifacts:
  files:
    - '*/'